sampling_pipelines:
  - name: "official"
    weight: 1
    processors:
      - name: "top_k"
        params:
          top_k: 64
      - name: "top_p"
        params:
          top_p: 0.95
  - name: "top-k 32"
    weight: 1
    processors:
      - name: "top_k"
        params:
          top_k: 32
  - name: "top-k 64"
    weight: 1
    processors:
      - name: "top_k"
        params:
          top_k: 64
  - name: "top-p 0.9"
    weight: 1
    processors:
      - name: "top_p"
        params:
          top_p: 0.9
  - name: "top-p 0.95"
    weight: 1
    processors:
      - name: "top_p"
        params:
          top_p: 0.95
  - name: "official temp 0.8"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 0.8
      - name: "top_k"
        params:
          top_k: 64
      - name: "top_p"
        params:
          top_p: 0.95
  - name: "top-k 32 temp 0.8"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 0.8
      - name: "top_k"
        params:
          top_k: 32
  - name: "top-k 64 temp 0.8"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 0.8
      - name: "top_k"
        params:
          top_k: 64
  - name: "top-p 0.9 temp 0.8"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 0.8
      - name: "top_p"
        params:
          top_p: 0.9
  - name: "top-p 0.95 temp 0.8"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 0.8
      - name: "top_p"
        params:
          top_p: 0.95
  - name: "official temp 1.2"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 1.2
      - name: "top_k"
        params:
          top_k: 64
      - name: "top_p"
        params:
          top_p: 0.95
  - name: "top-k 32 temp 1.2"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 1.2
      - name: "top_k"
        params:
          top_k: 32
  - name: "top-k 64 temp 1.2"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 1.2
      - name: "top_k"
        params:
          top_k: 64
  - name: "top-p 0.9 temp 1.2"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 1.2
      - name: "top_p"
        params:
          top_p: 0.9
  - name: "top-p 0.95 temp 1.2"
    weight: 1
    processors:
      - name: "temperature"
        params:
          temperature: 1.2
      - name: "top_p"
        params:
          top_p: 0.95
