data_path: "/mnt/data/combined_small.jsonl"
output_path: "/mnt/data/quality_labelled_combined_small.jsonl"

prompt_key: "prompt"
generation_key: "generation"
heuristic_key: "sampler_info"

reward_model_backend: "sglang"

model_name_or_path: "/mnt/data/llms/GRAM-LLaMA3.2-3B-RewardModel"
sglang_url: "http://127.0.0.1:30000/v1"
url: "http://127.0.0.1:30000/v1"

# Total rounds will be log2(num_players) + tournament_extra_rounds
tournament_extra_rounds: 1
